# Generated by Django 4.1.3 on 2023-01-25 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagenumber', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrolled_by',
        ),
    ]
